ldap:
  build: ldap
  hostname: ldap
  domainname: localdomain
  ports:
    - "9005:80"
    - "9010:389"
    - "9011:636"

sdhapi:
  build: sdhapi
  hostname: sdhapi
  domainname: localdomain
  links:
    - ldap:ldap
  environment:
    - USERPROFILE=/usr/lib/node_modules/sdh-api
    - SDH_API_HOST=
    - SDH_API_PATH=
    - SDH_API_PROTOCOL=
    - SDH_API_PORT=
    - SDH_LDAP_HOST=
    - SDH_LDAP_PASSWORD=
    - SDH_RABBIT_HOST=
    - SDH_RABBIT_PORT=
    - TERM=xterm
  ports:
    - "9002:8080"

mysql:
  build: mysql
  hostname: mysql
  domainname: localdomain
  environment:
    - MYSQL_PASS=secret

phpmyadmin:
  hostname: phpmyadmin
  domainname: localdomain
  image: smartdeveloperhub/phpmyadmin
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=secret
    - MYSQL_ADDR=mysql
    - MYSQL_PORT=3306

  links:
    - mysql:mysql

laravelweb:
  hostname: laravelweb
  domainname: localdomain
  build: laravel
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=secret
    - MYSQL_ADDR=mysql
    - MYSQL_PORT=3306
    - SDH_API_HOST=https://WEB_HOST/sdhapi
    - SDH_API_INTERNAL=http://sdhapi:8080/sdhapi
    - LARAVEL_DB=homestead
  links:
    - mysql:mysql
    - sdhapi:api
  ports:
    - "9000:80"

nginx:
  hostname: nginx
  domainname: localdomain
  build: nginx
  links:
    - sdhapi:sdhapi
    - laravelweb:laravelweb
  volumes:
    - /home/admin-com/ssl:/opt/ssl
  ports:
    - "80:80"
    - "443:443"
