mysql:
  hostname: mysql
  domainname: localdomain
  image: smartdeveloperhub/mysql  
  environment:
    - MYSQL_PASS=secret

phpmyadmin:
  hostname: phpmyadmin
  domainname: localdomain
  image: smartdeveloperhub/phpmyadmin
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=secret
    - MYSQL_ADDR=mysql
    - MYSQL_PORT=3306
  links:
    - mysql:mysql

laravel:
  hostname: laravel
  domainname: localdomain
  build: laravel
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=secret
    - MYSQL_ADDR=mysql
    - MYSQL_PORT=3306
    - SDH_API=
    - SDH_API_INTERNAL=
    - DB_DATABASE=homestead
  links:
    - mysql:mysql
  ports:
    - "9000:80"
