#!/bin/sh
 
ROOT=$(pwd)
SDHNAME="sdh-api"

Update() {
    cd /usr/lib
    if [ ! -d node_modules/$1 ]
    then
        npm install $1
    else
    	npm update
    fi

    cd node_modules/$1
    node index.js &
    cd $ROOT
}

echo "> SDH API"
Update $SDHNAME
